export const imageMap: Record<string, any> = {
  'vipera_berus.jpg': require('../../assets/images/vipera_berus.jpg'),
  'crotalus_atrox.jpg': require('../../assets/images/crotalus_atrox.jpg'),
  'agkistrodon_contortrix.jpg': require('../../assets/images/agkistrodon_contortrix.jpg'),
  'agkistrodon_piscivorus.jpg': require('../../assets/images/agkistrodon_piscivorus.jpg'),
  'vipera_aspis.jpg': require('../../assets/images/vipera_aspis.jpg'),
  'crotalus_oreganus.jpg': require('../../assets/images/crotalus_oreganus.jpg'),
  'crotalus_viridis.jpg': require('../../assets/images/crotalus_viridis.jpg'),
  'crotalus_helleri.jpg': require('../../assets/images/crotalus_helleri.jpg'),
  'crotalus_horridus.jpg': require('../../assets/images/crotalus_horridus.jpg'),
  'crotalus_cerastes.jpg': require('../../assets/images/crotalus_cerastes.jpg'),
  'crotalus_scutulatus.jpg': require('../../assets/images/crotalus_scutulatus.jpg'),
  'crotalus_ruber.jpg': require('../../assets/images/crotalus_ruber.jpg'),
  'gloydius_ussuriensis.jpg': require('../../assets/images/gloydius_ussuriensis.jpg'),
  'sistrurus_miliarius.jpg': require('../../assets/images/sistrurus_miliarius.jpg'),
  'crotalus_molossus.jpg': require('../../assets/images/crotalus_molossus.jpg'),
  'bothrops_asper.jpg': require('../../assets/images/bothrops_asper.jpg'),
  'crotalus_adamanteus.jpg': require('../../assets/images/crotalus_adamanteus.jpg'),
  'bothrops_alternatus.jpg': require('../../assets/images/bothrops_alternatus.jpg'),
  'crotalus_lutosus.jpg': require('../../assets/images/crotalus_lutosus.jpg'),
  'crotalus_durissus.jpg': require('../../assets/images/crotalus_durissus.jpg'),
  'bothrops_jararaca.jpg': require('../../assets/images/bothrops_jararaca.jpg'),
  'crotalus_pyrrhus.jpg': require('../../assets/images/crotalus_pyrrhus.jpg'),
  'protobothrops_mucrosquamatus.jpg': require('../../assets/images/protobothrops_mucrosquamatus.jpg'),
  'bothrops_atrox.jpg': require('../../assets/images/bothrops_atrox.jpg'),
  'bitis_arietans.jpg': require('../../assets/images/bitis_arietans.jpg'),
};
